parameters:

  #后台扫描二维码签到配置

  #web socket url
  web_socket_server: 'ws://127.0.0.1:8080/'

  #签到二维码
  qrcode_uri: 'http://127.0.0.1/backend/wx'
  qrcode_path: '%kernel.project_dir%/public/upload/qrcode'

  ##金秋app 微信
  jq_app_wx_id: '%env(JQ_APP_WX_ID)%'
  jq_app_wx_secret: '%env(JQ_APP_WX_SECRET)%'
  jq_app_wx_mch_id: '%env(JQ_APP_WX_MCH_ID)%'
  jq_app_wx_mch_secret: '%env(JQ_APP_WX_MCH_SECRET)%'
  jq_app_wxpay_notify_url: '%env(JQ_APP_WXPAY_NOTIFY_URL)%'

  ##佐商公众号 微信##
  jq_gzh_wx_id: '%env(JQ_GZH_WX_ID)%'
  jq_gzh_wx_secret: '%env(JQ_GZH_WX_SECRET)%'

  ##金秋app 支付宝
  jq_app_alipay_id: '%env(JQ_APP_ALIPAY_ID)%'
  jq_app_alipay_mch_private_key: '%env(JQ_APP_ALIPAY_MCH_PRIVATE_KEY)%'
  jq_app_alipay_public_key: '%env(JQ_APP_ALIPAY_PUBLIC_KEY)%'
  jq_app_alipay_notify_url: '%env(JQ_APP_ALIPAY_NOTIFY_URL)%'



  ##金秋app 银联
  jq_yinlian_url: '%env(JQ_APP_YINLIAN_URL)%'
  jq_yinlian_cehid: '%env(JQ_APP_YINLIAN_MCHID)%'
  jq_yinlian_key: '%env(JQ_APP_YINLIAN_KEY)%'
  jq_yinlian_notify_url: '%env(JQ_APP_YINLIAN_NOTIFY_URL)%'
  jq_yinlian_sub_appid: '%env(JQ_APP_YINLIAN_SUB_APPID)%'
  jq_app_yinlian_id: '%env(JQ_APP_YINLIAN_ID)%'
  