parameters:

  #后台扫描二维码签到配置

  #web socket url
  web_socket_server: 'ws://127.0.0.1:8080/'

  #签到二维码
  qrcode_uri: 'http://127.0.0.1/backend/wx'
  qrcode_path: '%kernel.project_dir%/public/upload/qrcode'



